'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CATEGORIAS
    Public Property id_categoria As Byte
    Public Property categoria As String
    Public Property eliminado As String

    Public Overridable Property TIPOS_DE_PRODUCTOS As ICollection(Of TIPOS_DE_PRODUCTOS) = New HashSet(Of TIPOS_DE_PRODUCTOS)

End Class
