'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DB_VIVEROEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DB_VIVEROEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CATEGORIAS() As DbSet(Of CATEGORIAS)
    Public Overridable Property CLIENTES() As DbSet(Of CLIENTES)
    Public Overridable Property FACTURAS() As DbSet(Of FACTURAS)
    Public Overridable Property FACTURAS_DETALLE() As DbSet(Of FACTURAS_DETALLE)
    Public Overridable Property FORMAS_DE_PAGO() As DbSet(Of FORMAS_DE_PAGO)
    Public Overridable Property PERFILES() As DbSet(Of PERFILES)
    Public Overridable Property PRODUCTOS() As DbSet(Of PRODUCTOS)
    Public Overridable Property TIPOS_DE_PRODUCTOS() As DbSet(Of TIPOS_DE_PRODUCTOS)
    Public Overridable Property USUARIOS() As DbSet(Of USUARIOS)

End Class
