'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FACTURAS
    Public Property num_factura As Integer
    Public Property fecha_y_hora As Date
    Public Property id_vendedor As Short
    Public Property id_FdePago As Byte
    Public Property id_cliente As Integer
    Public Property total As Double
    Public Property anulado As String

    Public Overridable Property CLIENTES As CLIENTES
    Public Overridable Property FACTURAS_DETALLE As ICollection(Of FACTURAS_DETALLE) = New HashSet(Of FACTURAS_DETALLE)
    Public Overridable Property FORMAS_DE_PAGO As FORMAS_DE_PAGO
    Public Overridable Property USUARIOS As USUARIOS

End Class
