'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FACTURAS_DETALLE
    Public Property num_factura As Integer
    Public Property id_item As Byte
    Public Property id_producto As Integer
    Public Property descripcion As String
    Public Property precio As Double
    Public Property cantidad As Short
    Public Property sub_total As Double

    Public Overridable Property FACTURAS As FACTURAS
    Public Overridable Property PRODUCTOS As PRODUCTOS

End Class
