'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PRODUCTOS
    Public Property id_categoria As Byte
    Public Property id_tipo As Short
    Public Property id_producto As Integer
    Public Property nombre As String
    Public Property descripcion As String
    Public Property tamanio As String
    Public Property disponible As String
    Public Property stock_min As Byte
    Public Property stock As Short
    Public Property precio_lista As Double
    Public Property precio_venta As Double
    Public Property descuento As Byte
    Public Property veces_vendido As Integer
    Public Property eliminado As String

    Public Overridable Property FACTURAS_DETALLE As ICollection(Of FACTURAS_DETALLE) = New HashSet(Of FACTURAS_DETALLE)
    Public Overridable Property TIPOS_DE_PRODUCTOS As TIPOS_DE_PRODUCTOS

End Class
