'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USUARIOS
    Public Property id_perfil As Byte
    Public Property id_usuario As Short
    Public Property DNI As Integer
    Public Property apellido As String
    Public Property nombre As String
    Public Property fecha_nac As Date
    Public Property fecha_ingreso As Date
    Public Property username As String
    Public Property contraseña As String
    Public Property direccion As String
    Public Property telefono As String
    Public Property email As String
    Public Property eliminado As String

    Public Overridable Property FACTURAS As ICollection(Of FACTURAS) = New HashSet(Of FACTURAS)
    Public Overridable Property PERFILES As PERFILES

End Class
